services:
  mysql:
    image: mysql:latest
    container_name: wnf-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fresh_food
    ports:
      - "3307:3306"
    volumes:
      - pawelbugiel-wnf-db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  backend:
    image: ghcr.io/pawelbugiel/waste_no_food/wnf-backend:${BACKEND_VERSION}
    container_name: wnf-backend-container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fresh_food?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: ghcr.io/pawelbugiel/waste_no_food/wnf-frontend:${FRONTEND_VERSION}
    container_name: wnf-frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pawelbugiel-wnf-db-data: {}

networks:
  app-network:
    driver: bridge